name: Deploy

on:
  push:
    branches:
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # se você tiver um arquivo requirements.txt

    - name: Run tests 
      run: |
        python -m unittest discover

    - name: Deploy application
      run: |
        # Comandos para implantar sua aplicação
        # Por exemplo, você pode executar um script que inicia sua aplicação

